from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(815, 460)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(True)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.gridLayout.addWidget(self.name_label, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.active_order = QtWidgets.QWidget()
        self.active_order.setObjectName("active_order")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.active_order)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.active_order)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.order_widg_1 = QtWidgets.QWidget()
        self.order_widg_1.setGeometry(QtCore.QRect(0, 0, 771, 361))
        self.order_widg_1.setObjectName("order_widg_1")
        self.formLayout = QtWidgets.QFormLayout(self.order_widg_1)
        self.formLayout.setObjectName("formLayout")
        self.order_lbl_1 = QtWidgets.QLabel(self.order_widg_1)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(15)
        font.setBold(False)
        self.order_lbl_1.setFont(font)
        self.order_lbl_1.setObjectName("order_lbl_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.order_lbl_1)
        self.order_btn_1 = QtWidgets.QPushButton(self.order_widg_1)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.order_btn_1.setFont(font)
        self.order_btn_1.setAutoFillBackground(False)
        self.order_btn_1.setAutoDefault(False)
        self.order_btn_1.setDefault(False)
        self.order_btn_1.setFlat(False)
        self.order_btn_1.setObjectName("order_btn_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.order_btn_1)
        self.scrollArea_2.setWidget(self.order_widg_1)
        self.gridLayout_4.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.active_order, "")
        self.close_order = QtWidgets.QWidget()
        self.close_order.setObjectName("close_order")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.close_order)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.close_order)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 771, 361))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout_2 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.close_order, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name_label.setText(_translate("MainWindow", "Кухня"))
        self.order_lbl_1.setText(_translate("MainWindow", "Круассан с лососем | 14:48   "))
        self.order_btn_1.setText(_translate("MainWindow", "Готов"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.active_order), _translate("MainWindow", "Активные"))
        self.label.setText(_translate("MainWindow", "Круассан с лососем | 14:48 | 15:35"))
        self.pushButton.setText(_translate("MainWindow", "Готов"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.close_order), _translate("MainWindow", "Закрытые"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
